language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.3

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COVERAGE=true
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" TEST_COMMAND="composer test-ci"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - travis_wait $TEST_COMMAND
    - composer normalize --dry-run
    - if [[ "$COVERAGE" = true ]]; then vendor/bin/php-cs-fixer fix --dry-run --diff; fi

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
