dist: trusty

language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci"

before_install:
    - travis_retry composer self-update
    - phpenv config-rm xdebug.ini || true
    - if [[ "$COVERAGE" = true ]]; then wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar; fi

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - travis_wait $TEST_COMMAND
    - if [[ "$COVERAGE" = true ]]; then php php-cs-fixer-v2.phar --dry-run --diff; fi

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
