language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.3

env:
    global:
        - TEST_COMMAND="composer test"

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COVERAGE=true TEST_COMMAND="composer test-ci"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --ignore-platform-reqs
    - if [[ $COVERAGE = true ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar; fi
    - if [[ $COVERAGE = true ]]; then chmod +x coveralls.phar; fi

script:
    - travis_wait $TEST_COMMAND
    - composer normalize --dry-run
    - if [[ $COVERAGE = true ]]; then vendor/bin/php-cs-fixer fix --dry-run --diff; fi

after_script:
    - if [[ $COVERAGE = true ]]; then ./coveralls.phar -v; fi
