name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/
          key: composer-7.4-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 8.0
          extensions: mbstring, fileinfo, json, intl, dom
      - name: install
        run: composer update --prefer-stable
      - name: 'php-cs-fixer check'
        run: 'vendor/bin/php-cs-fixer fix --dry-run --diff'
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions:  ['7.3', '7.4', '8.0', '8.1', '8.2']
    name: tests-${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/
          key: composer-${{ matrix.php-versions }}-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-stable
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer-lowest
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/
          key: composer-lowest-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 7.3
          extensions: mbstring, fileinfo, json, intl, dom
      - name: composer install
        run: composer update --prefer-lowest --prefer-stable
      - name: install prism
        run: curl -L https://raw.githack.com/stoplightio/prism/master/install | sh
      - name: run OpenApi3 prism server
        run: nohup prism mock src/Component/OpenApi3/Tests/client/openapi.yaml -p 4010 &
      - name: run OpenApi2 prism server
        run: nohup prism mock src/Component/OpenApi2/Tests/client/swagger.yaml -p 4011 &
      - name: tests
        run: vendor/bin/phpunit --exclude-group none
