name: CI
on: [push, pull_request]
jobs:
    cs-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: composer install
              uses: nick-zh/composer-php@master
              with:
                action: 'update'
            - name: php-cs-fixer check
              id: cs-fix
              uses:  actions/php-cs-fixer-check@v1
              with:
                args: '--diff --dry-run'
            - name: php-ce-fixer output
                run: echo "The time was ${{ steps.cs-fix.outputs.results }}"
