name: gitsplit
on:
  push:
    branches:
      - next
  release:
    types: [published]
jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://github.com/janephp/janephp /home/runner/work/janephp/janephp && cd /home/runner/work/janephp/janephp
      - name: use gitsplit older
        run: ln -s /home/runner/work/janephp/janephp/.github/gitsplit/older/.gitsplit /github/workspace/.gitsplit
      - name: gitsplit-older
        uses: docker://jderusse/gitsplit:latest
        with:
          args: gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      - name: use gitsplit 7-plus
        run: rm /github/workspace/.gitsplit && ln -s /home/runner/work/janephp/janephp/.github/gitsplit/7-plus/.gitsplit /github/workspace/.gitsplit
      - name: gitsplit-7-plus
        uses: docker://jderusse/gitsplit:latest
        with:
          args: gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
