name: gitsplit
on:
  push:
    branches:
      - next
  release:
    types: [published]
jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://github.com/janephp/janephp /home/runner/work/janephp/janephp && cd /home/runner/work/janephp/janephp
      - name: gitsplit-older
        uses: docker://jderusse/gitsplit:latest
        working-directory: /home/runner/work/janephp/janephp/.github/gitsplit/older
        with:
          args: gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      - name: gitsplit-7-plus
        uses: docker://jderusse/gitsplit:latest
        working-directory: /home/runner/work/janephp/janephp/.github/gitsplit/7-plus
        with:
          args: gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
