name: gitsplit
on:
  push:
    branches:
      - next
  release:
    types: [published]
jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: gitsplit
        run: docker run --rm -t -e GH_TOKEN -v /cache/gitsplit:/cache/gitsplit -v ${PWD}:/srv jderusse/gitsplit gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
