name: gitsplit
on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://github.com/janephp/janephp /home/runner/work/janephp/janephp && cd /home/runner/work/janephp/janephp
      - name: gitsplit
        run: docker run --rm -t -e GH_TOKEN -v /cache/gitsplit:/cache/gitsplit -v ${PWD}:/srv jderusse/gitsplit gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
